name: IPO Scanner v2

on:
  schedule:
    - cron: '18 09 * * *'     # TEST: 2:48 PM IST (9:18 AM UTC) - for immediate testing  
    - cron: '45 08 * * 1-5'   # Daily scan: 2:15 PM IST (8:45 AM UTC) - Weekdays only
    - cron: '15 09 * * 0'     # Weekly summary: Sunday 2:45 PM IST (9:15 AM UTC)
    - cron: '15 09 1 * *'     # Monthly review: 1st of month 2:45 PM IST (9:15 AM UTC)
  workflow_dispatch:
    inputs:
      mode:
        description: 'scan | stop_loss_update | weekly_summary | monthly_review | heartbeat'
        required: true
        default: 'scan'
        type: choice
        options:
          - scan
          - stop_loss_update
          - weekly_summary
          - monthly_review
          - heartbeat
      environment:
        description: 'Environment to use (production, staging, development)'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Cache TA-Lib installation
        id: cache-talib
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/lib/libta_lib.so*
            /usr/local/include/ta-lib
            /usr/local/bin/ta-config
          key: talib-Linux-v3
          restore-keys: |
            talib-Linux-v2
            talib-Linux-v1
            talib-Linux-

      - name: Install TA-Lib
        run: |
          if python -c "import talib" 2>/dev/null; then
            echo "✅ TA-Lib already available"
            exit 0
          fi
          
          if [ -f "/usr/local/lib/libta_lib.so" ] && [ -d "/usr/local/include/ta-lib" ]; then
            echo "✅ Found cached TA-Lib, installing Python package..."
            pip install TA-Lib
            echo "✅ Python TA-Lib package installed from cache"
            exit 0
          fi
          
          echo "TA-Lib not found, building from source..."
          sudo apt-get update
          sudo apt-get install -y build-essential wget
          
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr/local
          make
          sudo make install
          sudo ldconfig
          
          echo "✅ TA-Lib built and installed"
      
      - name: Clean up old Python caches
        run: |
          echo "Cleaning up old Python cache directories..."
          rm -rf ~/.cache/pip-old 2>/dev/null || true
          echo "Old Python caches cleaned up"
      
      - name: Cache Python dependencies
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-v1-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Show workflow mode and timing
        run: |
          echo "🚀 =========================================="
          echo "🚀 IPO Scanner Workflow Started"
          echo "🚀 =========================================="
          echo "📅 Current UTC: $(date -u +%Y-%m-%d\ %H:%M:%S)"
          echo "📅 Current IST: $(TZ='Asia/Kolkata' date +%Y-%m-%d\ %H:%M:%S)"
          echo "🔄 Event: ${{ github.event_name }}"
          echo "📋 Branch: ${{ github.ref }}"
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "🎯 Mode: ${{ github.event.inputs.mode }} (Manual Trigger)"
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            echo "⏰ Schedule that triggered: ${{ github.event.schedule }}"
            echo "📊 Mode: Scheduled Run"
          else
            echo "🎯 Mode: Default (scan)"
          fi
          echo "🚀 =========================================="
      
      - name: Debug environment variables
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          IPO_YEARS_BACK: ${{ secrets.IPO_YEARS_BACK }}
          STOP_PCT: ${{ vars.STOP_PCT || '0.03' }}
          PT_A_PLUS: ${{ vars.PT_A_PLUS || '0.15' }}
          PT_B: ${{ vars.PT_B || '0.12' }}
          PT_C: ${{ vars.PT_C || '0.10' }}
          CONSOL_WINDOWS: ${{ vars.CONSOL_WINDOWS || '10,20,40,80,120' }}
          VOL_MULT: ${{ vars.VOL_MULT || '1.2' }}
          ABS_VOL_MIN: ${{ vars.ABS_VOL_MIN || '3000000' }}
          LOOKAHEAD: ${{ vars.LOOKAHEAD || '80' }}
          MAX_DAYS: ${{ vars.MAX_DAYS || '200' }}
          MAX_FLAT_HOLD_WEEKS: ${{ vars.MAX_FLAT_HOLD_WEEKS || '20' }}
          CACHE_FILE: ${{ vars.CACHE_FILE || 'ipo_cache.pkl' }}
          SIGNALS_CSV: ${{ vars.SIGNALS_CSV || 'ipo_signals.csv' }}
          POSITIONS_CSV: ${{ vars.POSITIONS_CSV || 'ipo_positions.csv' }}
          HEARTBEAT_RUNS: ${{ vars.HEARTBEAT_RUNS || '0' }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL || 'INFO' }}
        run: |
          echo "=== Environment Variables Debug ==="
          echo "🔐 Secrets:"
          echo "TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:0:10}..." 
          echo "TELEGRAM_CHAT_ID: $TELEGRAM_CHAT_ID"
          echo "IPO_YEARS_BACK: $IPO_YEARS_BACK"
          echo ""
          echo "⚙️ Variables:"
          echo "STOP_PCT: $STOP_PCT"
          echo "PT_A_PLUS: $PT_A_PLUS, PT_B: $PT_B, PT_C: $PT_C"
          echo "CONSOL_WINDOWS: $CONSOL_WINDOWS"
          echo "VOL_MULT: $VOL_MULT, ABS_VOL_MIN: $ABS_VOL_MIN"
          echo "LOOKAHEAD: $LOOKAHEAD, MAX_DAYS: $MAX_DAYS"
          echo "=================================="
          
          if [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "❌ ERROR: TELEGRAM_CHAT_ID is empty!"
            exit 1
          else
            echo "✅ TELEGRAM_CHAT_ID is set: $TELEGRAM_CHAT_ID"
          fi
          
          if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
            echo "❌ ERROR: TELEGRAM_BOT_TOKEN is empty!"
            exit 1
          else
            echo "✅ TELEGRAM_BOT_TOKEN is set (length: ${#TELEGRAM_BOT_TOKEN})"
          fi
      
      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          IPO_YEARS_BACK: ${{ secrets.IPO_YEARS_BACK }}
          STOP_PCT: ${{ vars.STOP_PCT || '0.03' }}
          PT_A_PLUS: ${{ vars.PT_A_PLUS || '0.15' }}
          PT_B: ${{ vars.PT_B || '0.12' }}
          PT_C: ${{ vars.PT_C || '0.10' }}
          CONSOL_WINDOWS: ${{ vars.CONSOL_WINDOWS || '10,20,40,80,120' }}
          VOL_MULT: ${{ vars.VOL_MULT || '1.2' }}
          ABS_VOL_MIN: ${{ vars.ABS_VOL_MIN || '3000000' }}
          LOOKAHEAD: ${{ vars.LOOKAHEAD || '80' }}
          MAX_DAYS: ${{ vars.MAX_DAYS || '200' }}
          MAX_FLAT_HOLD_WEEKS: ${{ vars.MAX_FLAT_HOLD_WEEKS || '20' }}
          CACHE_FILE: ${{ vars.CACHE_FILE || 'ipo_cache.pkl' }}
          SIGNALS_CSV: ${{ vars.SIGNALS_CSV || 'ipo_signals.csv' }}
          POSITIONS_CSV: ${{ vars.POSITIONS_CSV || 'ipo_positions.csv' }}
          HEARTBEAT_RUNS: ${{ vars.HEARTBEAT_RUNS || '0' }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL || 'INFO' }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            MODE="${{ github.event.inputs.mode }}"
            if [ -z "$MODE" ]; then
              MODE="scan"
            fi
            echo "🎯 Running manual trigger in mode: $MODE"
            python streamlined-ipo-scanner.py $MODE
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            echo "⏰ Running scheduled workflow"
            echo "📋 Schedule that triggered: ${{ github.event.schedule }}"
            
            # Use the actual cron expression that triggered this run
            SCHEDULE="${{ github.event.schedule }}"
            
            case "$SCHEDULE" in
              "18 09 * * *")
                echo "✅ TEST SCHEDULE: Running test scan (2:48 PM IST)"
                python streamlined-ipo-scanner.py scan
                echo "Test completed - checking stop losses..."
                python streamlined-ipo-scanner.py stop_loss_update
                ;;
              "45 08 * * 1-5")
                echo "✅ DAILY SCAN: Running weekday scan (2:15 PM IST)"  
                python streamlined-ipo-scanner.py scan
                python streamlined-ipo-scanner.py stop_loss_update
                ;;
              "15 09 * * 0")
                echo "✅ WEEKLY SUMMARY: Running Sunday summary (2:45 PM IST)"
                python streamlined-ipo-scanner.py weekly_summary
                ;;
              "15 09 1 * *")
                echo "✅ MONTHLY REVIEW: Running monthly review (2:45 PM IST)"
                python streamlined-ipo-scanner.py monthly_review
                ;;
              *)
                echo "⚠️ UNKNOWN SCHEDULE: $SCHEDULE - Running default scan"
                echo "This might be your old schedule that's still active"
                python streamlined-ipo-scanner.py scan
                ;;
            esac
          else
            echo "🔄 DEFAULT: Running default mode: scan"
            python streamlined-ipo-scanner.py scan
          fi
      
      - name: Upload CSV files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ipo-data-${{ github.run_number }}
          path: |
            ipo_signals.csv
            ipo_positions.csv
            recent_ipo_symbols.csv
          retention-days: 30
          if-no-files-found: warn
      
      - name: Commit and push CSV files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          files_to_add=""
          if [ -f "ipo_signals.csv" ]; then
            files_to_add="$files_to_add ipo_signals.csv"
          fi
          if [ -f "ipo_positions.csv" ]; then
            files_to_add="$files_to_add ipo_positions.csv"
          fi
          if [ -f "recent_ipo_symbols.csv" ]; then
            files_to_add="$files_to_add recent_ipo_symbols.csv"
          fi
          
          if [ -n "$files_to_add" ]; then
            git add -f $files_to_add
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update IPO data - ${{ github.run_number }} [skip ci]"
              git push
            fi
          else
            echo "No CSV files found to commit"
          fi
