name: IPO Scanner v2

on:
  schedule:
    - cron: '30 14 * * 1-5'   # Daily scan at 2:30 PM IST
    - cron: '0 18 * * 1-5'    # Stop-loss update at 6:00 PM IST
    - cron: '30 14 * * 0'     # Weekly summary, Sunday
    - cron: '0 15 1 * *'      # Monthly review, 1st of month
  workflow_dispatch:
    inputs:
      mode:
        description: 'scan | stop_loss_update | weekly_summary | monthly_review | heartbeat'
        required: true
        default: 'scan'
        type: choice
        options:
          - scan
          - stop_loss_update
          - weekly_summary
          - monthly_review
          - heartbeat

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Cache TA-Lib installation
        id: cache-talib
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/libta_lib.so
          key: talib-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
      
      - name: Install system dependencies
        if: steps.cache-talib.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr/local
          make
          sudo make install
          sudo ldconfig
      
      - name: Cache Python dependencies
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          IPO_YEARS_BACK: ${{ secrets.IPO_YEARS_BACK }}
        run: |
          # Check if mode was provided via workflow_dispatch
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.mode }}" ]; then
            echo "Running in manual mode: ${{ github.event.inputs.mode }}"
            python streamlined-ipo-scanner.py ${{ github.event.inputs.mode }}
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            echo "Running scheduled workflow"
            case "${{ github.schedule }}" in
              "30 14 * * 1-5") python streamlined-ipo-scanner.py scan ;;
              "0 18 * * 1-5") python streamlined-ipo-scanner.py stop_loss_update ;;
              "30 14 * * 0") python streamlined-ipo-scanner.py weekly_summary ;;
              "0 15 1 * *") python streamlined-ipo-scanner.py monthly_review ;;
              *) python streamlined-ipo-scanner.py scan ;;
            esac
          else
            echo "Running default mode: scan"
            python streamlined-ipo-scanner.py scan
          fi
      
      - name: Upload CSV files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ipo-data-${{ github.run_number }}
          path: |
            ipo_signals.csv
            ipo_positions.csv
            recent_ipo_symbols.csv
          retention-days: 30
          if-no-files-found: warn
      
      - name: Commit and push CSV files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check which files exist before adding them
          files_to_add=""
          if [ -f "ipo_signals.csv" ]; then
            files_to_add="$files_to_add ipo_signals.csv"
          fi
          if [ -f "ipo_positions.csv" ]; then
            files_to_add="$files_to_add ipo_positions.csv"
          fi
          if [ -f "recent_ipo_symbols.csv" ]; then
            files_to_add="$files_to_add recent_ipo_symbols.csv"
          fi
          
          if [ -n "$files_to_add" ]; then
            # Force add files even if they're in .gitignore
            git add -f $files_to_add
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update IPO data - ${{ github.run_number }} [skip ci]"
              git push
            fi
          else
            echo "No CSV files found to commit"
          fi
