name: IPO Scanner

on:
  schedule:
    - cron: '30 14 * * 1-5'   # Daily scan
    - cron: '30 14 * * 0'     # Weekly summary, Sunday
    - cron: '30 15 * * 0'     # Monthly review, first Sunday
  workflow_dispatch:
    inputs:
      mode:
        description: 'scan | weekly_summary | monthly_review'
        required: true
        default: 'scan'

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          IPO_YEARS_BACK: ${{ secrets.IPO_YEARS_BACK }}
        run: python streamlined-ipo-scanner.py ${{ github.event.inputs.mode }}
      - uses: actions/upload-artifact@v3
        with:
          name: ipo_signals
          path: ipo_signals.csv
