name: IPO Scanner v2

on:
  schedule:
    - cron: '30 14 * * 1-5'   # Daily scan at 2:30 PM IST
    - cron: '0 18 * * 1-5'    # Stop-loss update at 6:00 PM IST
    - cron: '30 14 * * 0'     # Weekly summary, Sunday
    - cron: '0 15 1 * *'      # Monthly review, 1st of month
  workflow_dispatch:
    inputs:
      mode:
        description: 'scan | stop_loss_update | weekly_summary | monthly_review | heartbeat'
        required: true
        default: 'scan'
        type: choice
        options:
          - scan
          - stop_loss_update
          - weekly_summary
          - monthly_review
          - heartbeat

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Cache TA-Lib compiled binaries
        id: cache-talib
        uses: actions/cache@v4
        with:
          path: |
            talib-install/
          key: talib-binaries-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            talib-binaries-${{ runner.os }}-
      
      - name: Install TA-Lib (cached or build)
        run: |
          echo "Installing TA-Lib..."
          sudo apt-get update
          sudo apt-get install -y build-essential wget
          
          # Create cache directory
          mkdir -p talib-install
          
          if [ -d "talib-install" ] && [ "$(ls -A talib-install 2>/dev/null)" ]; then
            echo "Using cached TA-Lib installation..."
            sudo cp -r talib-install/* /usr/local/
            sudo ldconfig
            echo "✅ Cached TA-Lib restored"
          else
            echo "Building TA-Lib from source..."
            wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
            tar -xzf ta-lib-0.4.0-src.tar.gz
            cd ta-lib/
            ./configure --prefix=/usr/local
            make
            sudo make install
            sudo ldconfig
            
            # Cache the installation for next time
            echo "Caching TA-Lib installation..."
            sudo cp -r /usr/local/lib/libta_lib.so* talib-install/ 2>/dev/null || true
            sudo cp -r /usr/local/include/ta-lib talib-install/ 2>/dev/null || true
            sudo cp /usr/local/bin/ta-config talib-install/ 2>/dev/null || true
            
            # Ensure directory has content for caching
            if [ "$(ls -A talib-install 2>/dev/null)" ]; then
              echo "✅ TA-Lib built and cached"
            else
              echo "⚠️ Warning: No files cached (permission issue)"
            fi
          fi
      
      - name: Verify TA-Lib installation
        run: |
          echo "Verifying TA-Lib installation..."
          python -c "import talib; print('✅ TA-Lib is available')" || echo "❌ TA-Lib not available"
      
      - name: Cache Python dependencies
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Show workflow mode and timing
        run: |
          echo "🚀 =========================================="
          echo "🚀 IPO Scanner Workflow Started"
          echo "🚀 =========================================="
          echo "📅 Date: $(date)"
          echo "⏰ Time: $(date +%H:%M:%S)"
          echo "🔄 Event: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "🎯 Mode: ${{ github.event.inputs.mode }} (Manual Trigger)"
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            echo "⏰ Mode: Scheduled Run"
            echo "📋 Schedule: ${{ github.schedule }}"
            case "${{ github.schedule }}" in
              "30 14 * * 1-5") echo "📊 Scheduled Mode: Daily Scan (2:30 PM IST)" ;;
              "0 18 * * 1-5") echo "📊 Scheduled Mode: Stop-Loss Update (6:00 PM IST)" ;;
              "30 14 * * 0") echo "📊 Scheduled Mode: Weekly Summary (Sunday 2:30 PM IST)" ;;
              "0 15 1 * *") echo "📊 Scheduled Mode: Monthly Review (1st of month 3:00 PM IST)" ;;
              *) echo "📊 Scheduled Mode: Unknown" ;;
            esac
          else
            echo "🎯 Mode: Default (scan)"
          fi
          echo "🚀 =========================================="
      
      - name: Debug environment variables
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          IPO_YEARS_BACK: ${{ secrets.IPO_YEARS_BACK }}
        run: |
          echo "=== Environment Variables Debug ==="
          echo "TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:0:10}..." # Show first 10 chars
          echo "TELEGRAM_CHAT_ID: $TELEGRAM_CHAT_ID"
          echo "IPO_YEARS_BACK: $IPO_YEARS_BACK"
          echo "=================================="
          
          # Test if CHAT_ID is properly set
          if [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "❌ ERROR: TELEGRAM_CHAT_ID is empty!"
            exit 1
          else
            echo "✅ TELEGRAM_CHAT_ID is set: $TELEGRAM_CHAT_ID"
          fi
          
          # Test if BOT_TOKEN is properly set
          if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
            echo "❌ ERROR: TELEGRAM_BOT_TOKEN is empty!"
            exit 1
          else
            echo "✅ TELEGRAM_BOT_TOKEN is set (length: ${#TELEGRAM_BOT_TOKEN})"
          fi
      
      
      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          IPO_YEARS_BACK: ${{ secrets.IPO_YEARS_BACK }}
        run: |
          # Always use the provided mode for manual triggers
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            MODE="${{ github.event.inputs.mode }}"
            if [ -z "$MODE" ]; then
              MODE="scan"
            fi
            echo "Running manual trigger in mode: $MODE"
            python streamlined-ipo-scanner.py $MODE
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            echo "Running scheduled workflow"
            case "${{ github.schedule }}" in
              "30 14 * * 1-5") python streamlined-ipo-scanner.py scan ;;
              "0 18 * * 1-5") python streamlined-ipo-scanner.py stop_loss_update ;;
              "30 14 * * 0") python streamlined-ipo-scanner.py weekly_summary ;;
              "0 15 1 * *") python streamlined-ipo-scanner.py monthly_review ;;
              *) python streamlined-ipo-scanner.py scan ;;
            esac
          else
            echo "Running default mode: scan"
            python streamlined-ipo-scanner.py scan
          fi
      
      - name: Upload CSV files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ipo-data-${{ github.run_number }}
          path: |
            ipo_signals.csv
            ipo_positions.csv
            recent_ipo_symbols.csv
          retention-days: 30
          if-no-files-found: warn
      
      - name: Commit and push CSV files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check which files exist before adding them
          files_to_add=""
          if [ -f "ipo_signals.csv" ]; then
            files_to_add="$files_to_add ipo_signals.csv"
          fi
          if [ -f "ipo_positions.csv" ]; then
            files_to_add="$files_to_add ipo_positions.csv"
          fi
          if [ -f "recent_ipo_symbols.csv" ]; then
            files_to_add="$files_to_add recent_ipo_symbols.csv"
          fi
          
          if [ -n "$files_to_add" ]; then
            # Force add files even if they're in .gitignore
            git add -f $files_to_add
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update IPO data - ${{ github.run_number }} [skip ci]"
              git push
            fi
          else
            echo "No CSV files found to commit"
          fi
